server:
  port: 8081

spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:mysql://localhost:3306/loan_management_system
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

file:
  upload-dir: D:/akshays-workspace/Spring/loan-management-system/loan-service/uploads

aws:
  region: ap-south-1
  access-key: AKIAT33RCJ65647FECPX
  secret-key: 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
  bucket-name: loan-management-documentss